### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by jameshilliard**
This should get pynetsnmp running under python 3, this shouldn't have any python 2 regressions.

### CODE REVIEW

**Comment by jplouis** [comment]
Jenkins cannot run this build automatically. Can one of the admins verify this patch?  To kick off the pull verification add a comment with "ok to test".

**Comment by lunkwill42** [comment]
There are now three forks dealing with the issue of Python 3 compatibility (and a few other things), one from @kalombos, this one, and my own - but no feedback from @zenoss .

There is clearly an interested in having pynetsnmp work on Python 3. What can be done to get these changes merged and accepted into upstream? Or do we need to fork the entire library properly?

**Comment by jameshilliard** [comment]
Maybe it would be a good idea to try and upstream to the twisted project, although it would probably need to be re-licensed/dual licensed.

**Comment by lunkwill42** [comment]
Relicensing would still require some sort of feedback from @zenoss - which they haven't been very forthcoming with here on GitHub. I don't know anything about the inner workings of the ZenOSS project, my only interest is in the pynetsnmp library itself. Do you or @kalombos know anything about ZenOSS at all, or do we all just share an interest in pynetsnmp?

**Comment by kalombos** [comment]
I forked the [library](https://github.com/kalombos/pynetsnmp) and upload it on [pypi](https://pypi.python.org/pypi/pynetsnmp-2/). Welcome to contribute.

**Comment by lunkwill42** [comment]
I might just take you up on that offer, @kalombos. One fork is better than three. Your original PR #10 towards the @zenoss is still open, though, and keeps updating with every commit to your repo (I think that's why I keep getting notifications about your changes)

**Comment by csmouse** [comment]
PR has aged out. Closing.

**Pull request closed without merging**
